### ISSUE TITLE
希望能在python3.9用

### ISSUE THREAD

**Issue by Frocean** [mwbimh/nonebot_plugin_broker#1]
遇到的问题是这个：
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.10,<4.0; 0.2.0 Requires-Python >=3.10,<4.0; 0.3.0 Requires-Python >=3.10,<4.0; 0.4.0 Requires-Python >=3.10,<4.0
ERROR: Could not find a version that satisfies the requirement nonebot-plugin-broker (from versions: none)
ERROR: No matching distribution found for nonebot-plugin-broker

**Comment by mwbimh** [comment]
修好了应该，之前没在低版本测过
